### ISSUE TITLE
No output issue

### ISSUE THREAD

**Issue by flipkast** [fofr/cog-comfyui-xlabs-flux-controlnet#4]
Hi. We are getting from time to time the following issue

Running workflow
got prompt
Executing node 16, title: Load Image, class type: LoadImage
Executing node 54, title: Width and height for scaling image to ideal resolution 🪴, class type: Width and height for scaling image to ideal resolution 🪴
Executing node 55, title: 🔧 Image Resize, class type: ImageResize+
model_path is /src/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts/LiheYoung/Depth-Anything/checkpoints/depth_anything_vitl14.pth
Executing node 51, title: AIO Aux Preprocessor, class type: AIO_Preprocessor
using MLP layer as FFN
!!! Exception during processing !!! PytorchStreamReader failed reading zip archive: failed finding central directory
Traceback (most recent call last):
File "/src/ComfyUI/execution.py", line 316, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/src/ComfyUI/execution.py", line 191, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/src/ComfyUI/execution.py", line 168, in _map_node_over_list
process_inputs(input_dict, i)
File "/src/ComfyUI/execution.py", line 157, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "/src/ComfyUI/custom_nodes/comfyui_controlnet_aux/__init__.py", line 117, in execute
return getattr(aux_class(), aux_class.FUNCTION)(**params)
File "/src/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/depth_anything.py", line 19, in execute
model = DepthAnythingDetector.from_pretrained(filename=ckpt_name).to(model_management.get_torch_device())
File "/src/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/depth_anything/__init__.py", line 42, in from_pretrained
model.load_state_dict(torch.load(model_path, map_location="cpu"))
File "/root/.pyenv/versions/3.10.14/lib/python3.10/site-packages/torch/serialization.py", line 1072, in load
with _open_zipfile_reader(opened_file) as opened_zipfile:
File "/root/.pyenv/versions/3.10.14/lib/python3.10/site-packages/torch/serialization.py", line 480, in __init__
super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
Prompt executed in 3.19 seconds
outputs:  {}

**Comment by fofr** [comment]
Do you have an example of the zip you used with this?

**Comment by fofr** [comment]
I'm not sure of the exact cause but I've added some changes which should help:

- If the cause was corrupted depth anything weights, I've shifted downloads for this into setup to avoid that happening
- Errors are now reported, so the prediction will error out rather than return success with no outputs
